--Dropping the tables if they exist previously

DROP TABLE "CUSTOMERTRANSACTION";
DROP TABLE "DIM_CUSTOMER";
DROP TABLE "DIM_STORE";
DROP TABLE "DIM_PRODUCT";
DROP TABLE "DIM_DATE";
DROP TABLE "FACT_SALES";



--Creating the tables in DataWarehouse

CREATE TABLE "CUSTOMERTRANSACTION" (
 "ID" NUMBER(8,0) NOT NULL,
  "PRODUCT_ID" VARCHAR2(6) NOT NULL, 
  "CUSTOMER_ID" VARCHAR2(4) NOT NULL, 
  "CUSTOMER_NAME" VARCHAR2(30) NOT NULL, 
  "STORE_ID" VARCHAR2(4) NOT NULL, 
  "STORE_NAME" VARCHAR2(20) NOT NULL, 
  "T_DATE" DATE NOT NULL, 
  "QUANTITY" NUMBER(3,0) NOT NULL,
  "PRODUCT_NAME" VARCHAR2(30) NOT NULL, 
  "SUPPLIER_ID" VARCHAR2(5) NOT NULL, 
  "SUPPLIER_NAME" VARCHAR2(30) NOT NULL, 
  "TOTALSALE" NUMBER(5,2) DEFAULT (0.0) NOT NULL,
CONSTRAINT CUSTOMERTRANSACTION_PK PRIMARY KEY (ID));



Create TABLE "DIM_CUSTOMER"
(
    "CUSTOMER_ID" VARCHAR2(4) NOT NULL, 
    "CUSTOMER_NAME" VARCHAR2(30) NOT NULL,
    CONSTRAINT DIMCUSTOMER_PK PRIMARY KEY(CUSTOMER_ID));
   
CREATE TABLE "DIM_STORE"
(
    "STORE_ID" VARCHAR2(4) NOT NULL, 
    "STORE_NAME" VARCHAR2(20) NOT NULL,
    CONSTRAINT DIMSTORE_PK  PRIMARY KEY(STORE_ID));
    
CREATE TABLE "DIM_PRODUCT"
(
    "PRODUCT_ID" VARCHAR2(6) NOT NULL,
    "PRODUCT_NAME" VARCHAR2(30) NOT NULL,
    CONSTRAINT DIMPRODUCT_PK PRIMARY KEY(PRODUCT_ID));   


CREATE TABLE "DIM_SUPPLIER"
(
  "SUPPLIER_ID" VARCHAR2(5) NOT NULL, 
  "SUPPLIER_NAME" VARCHAR2(30) NOT NULL, 
    CONSTRAINT DIMSUPPLIER_PK PRIMARY KEY(SUPPLIER_ID));


CREATE TABLE "DIM_DATE"
(
    "DATE_ID" DATE NOT NULL, 
    "YEAR" VARCHAR2(6) NOT NULL,
    "MONTH" VARCHAR2(6) NOT NULL,
    "DAY" VARCHAR2(6) NOT NULL,
    CONSTRAINT DIMDATE_PK PRIMARY KEY (DATE_ID));   

CREATE TABLE "FACT_SALES"
(
    "ID" NUMBER(8,0) NOT NULL,
    "TRANSACTION_DATE" DATE NOT NULL, 
    "QUANTITY" NUMBER(3,0) NOT NULL,
    "TOTALSALE" NUMBER(5,2) DEFAULT (0.0) NOT NULL,
    "CUSTOMERKEY" VARCHAR2(4) NOT NULL, 
    "STOREKEY" VARCHAR2(4) NOT NULL, 
    "PRODUCTKEY" VARCHAR2(6) NOT NULL,
    "SUPPLIERKEY" VARCHAR2(5) NOT NULL, 
    CONSTRAINT FACTSALE_PK PRIMARY KEY (ID));



