
/*This is the script which read 50 tuples from TRANSACTIONS table as input data into a cursor. The cursor is a user
defined data type in PLSQL which works as a list and is used to store multiple records in
memory for processing*/


--Here the cursor and variables are declared
DECLARE
STR_CNT number(5) := 0;  
  CURSOR TRANS_CUR
  IS
    SELECT TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,CUSTOMER_NAME,STORE_ID,STORE_NAME,T_DATE,QUANTITY
    FROM 
        TRANSACTIONS;
  CURSOR MASTER_CUR
  IS
    SELECT PRODUCT_ID,PRODUCT_NAME,SUPPLIER_ID,SUPPLIER_NAME,PRICE
    FROM 
        MASTERDATA; 

--Our program start from here with begin statement
BEGIN
DBMS_OUTPUT.ENABLE (buffer_size => NULL);


--This is the INLJ algorithm which implements the INLJ and insert the data in the dimension and fact tables
FOR A IN 1 .. 200  LOOP
  FOR I IN (SELECT TRANSACTION_ID,PRODUCT_ID,CUSTOMER_ID,CUSTOMER_NAME,STORE_ID,STORE_NAME,T_DATE,QUANTITY FROM TRANSACTIONS
    WHERE
        TRANSACTION_ID BETWEEN STR_CNT+1 AND STR_CNT+50)
    LOOP
    FOR J IN MASTER_CUR
    LOOP
     IF I.PRODUCT_ID = J.PRODUCT_ID THEN
       INSERT INTO CUSTOMERTRANSACTION (ID,PRODUCT_ID,CUSTOMER_ID,CUSTOMER_NAME,STORE_ID,STORE_NAME,T_DATE,QUANTITY,PRODUCT_NAME,SUPPLIER_ID,SUPPLIER_NAME,TOTALSALE) 
       VALUES (I.TRANSACTION_ID,I.PRODUCT_ID,I.CUSTOMER_ID,I.CUSTOMER_NAME,I.STORE_ID,I.STORE_NAME,I.T_DATE,I.QUANTITY,J.PRODUCT_NAME,J.SUPPLIER_ID,J.SUPPLIER_NAME,(J.PRICE*I.QUANTITY));
       INSERT INTO FACT_SALES VALUES (I.TRANSACTION_ID,I.T_DATE,I.QUANTITY,(J.PRICE*I.QUANTITY),I.CUSTOMER_ID,I.STORE_ID,I.PRODUCT_ID,J.SUPPLIER_ID);
       --dbms_output.put_line(J.PRODUCT_NAME ||' '|| I.STORE_NAME ||' '|| J.SUPPLIER_ID ||'           '|| J.SUPPLIER_NAME);
     END IF;
    END LOOP;
  END LOOP;
  STR_CNT := STR_CNT + 50;
END LOOP;
INSERT INTO DIM_PRODUCT SELECT DISTINCT PRODUCT_ID, PRODUCT_NAME FROM CUSTOMERTRANSACTION;
INSERT INTO DIM_CUSTOMER SELECT DISTINCT CUSTOMER_ID, CUSTOMER_NAME FROM CUSTOMERTRANSACTION;
INSERT INTO DIM_STORE SELECT DISTINCT STORE_ID, STORE_NAME FROM CUSTOMERTRANSACTION;
INSERT INTO DIM_SUPPLIER SELECT DISTINCT SUPPLIER_ID, SUPPLIER_NAME  FROM CUSTOMERTRANSACTION;
INSERT INTO DIM_DATE Select DISTINCT T_DATE, to_char(T_DATE, 'YYYY'), to_char(T_DATE, 'MM'), to_char(T_DATE, 'DD') FROM CUSTOMERTRANSACTION;
END;


/*SELECT COUNT(*) FROM FACT_SALES;
SELECT COUNT(*) FROM DIM_CUSTOMER;
SELECT COUNT(*) FROM DIM_STORE;
SELECT COUNT(*) FROM DIM_SUPPLIER;
SELECT COUNT(*) FROM DIM_PRODUCT;
SELECT COUNT(*) FROM DIM_DATE;*/

